/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args){
        Restaurant newRestaurant = new Restaurant("aya",3);
        newRestaurant.addReview("heneen" , 7);

        System.out.println(newRestaurant);
    }
}
